name: Conjur Production Deployment
on:
    push:
        tags:
            - 'v*'

jobs:
    deploy:
        runs-on: conjur01
        environment: production
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy code
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ vars.TARGET_HOST_1 }}
                    username: ${{ vars.USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        if [ -d conjur ]; then 
                          echo Conjur directory existed
                          echo clean up for redeployment
                          cd conjur
                          podman-compose down
                          cd ..
                          rm -Rf conjur
                        fi
                        git clone https://github.com/GCLIM/conjur-quickstart.git conjur
                        cd conjur
                        git checkout production
                        python3 test_workflow.py

            # - name: Deploy to Remote Server
            #   run: |
            #     ssh ${{ vars.USER }}@${{ vars.TARGET_HOST_1 }} "git pull origin production && cd conjur-quickstarts && ./test_workflow.sh"
