name: Conjur Production Deployment
on:
    push:
        branches:
        - production 
jobs:
    deploy:
        runs-on: conjur01
        environment: production
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Deploy to Remote Server
              run: |
                ssh ${{ vars.USER }}@${{ vars.TARGET_HOST_1 }} "git pull origin master && cd conjur-quickstarts && ./test_workflow.sh"
