name: quick_start_flow_test
on:

  pull_request:
    branches:
    - main

jobs:

  tests:
    runs-on: conjur01

    steps:
      - uses: actions/checkout@v2
      - name: Run Worlflow Test Script
        run: python3 test_workflow.py
