name: Conjur Test Bot App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
    deploy:
        runs-on: conjur01
        environment: ${{ github.event.inputs.environment }}
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy code
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ vars.TARGET_HOST_1 }}
                    username: ${{ vars.USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        if [ -d conjur ]; then 
                          cd conjur
                          python3 test_botapp.py

                        fi
